---
- name: Provision EC2
  hosts: localhost
  connection: local
  module_defaults:
    group/aws:
      aws_access_key: '{{ aws_access_key }}'
      aws_secret_key: '{{ aws_secret_key }}'
      region: '{{ region }}'

  vars:
    key_name: mamendola-pem
    region: us-east-1
    image: ami-06640050dc3f556bb
    id: web-app
    instance_type: t3.micro
    subnet: subnet-03d84a11ebe272d96

  tasks:
    - name: Provision an EC2 instance with a public IP address
      amazon.aws.ec2_instance:
        name: ec2
        key_name: "{{ key_name }}"
        vpc_subnet_id: "{{ subnet }}"
        instance_type: "{{ instance_type }}"
        security_group: default
        network:
          assign_public_ip: true
        image_id: "{{ image }}"
        tags:
          Environment: Testing
      register: result

    - name: Add all instance public IPs to host group
      ansible.builtin.add_host:
        hostname: "{{ item.public_ip_address }}"
        groups: ec2hosts
        ansible_ssh_private_key_file: ~/.aws/mamendola-pem.pem
      loop: "{{ result.instances }}"

- name: Configure EC2
  hosts: ec2hosts
  remote_user: ec2-user
  become: true

  tasks:
    - name: Crear grupo admins
      ansible.builtin.group:
        name: admins
        state: present
    - name: Ensure user is present
      ansible.builtin.user:
        name: mauri
        shell: /bin/bash
        groups: admins
        append: true
