---
- name: Create users
  hosts: "{{ servidores }}"
  become: yes


  tasks:
    - name: Crear grupo admins
      ansible.builtin.group:
        name: admins
        state: present
    - name: Add users
      ansible.builtin.user:
        name: mauri
        shell: /bin/bash
        groups: admins
        append: true