---
- name: Create users
  hosts: "{{ servidores }}"
  become: yes


  tasks:
    - name: Add users
      ansible.builtin.user:
        name: mauri
        shell: /bin/bash
        groups: wheels
        append: true